---
# Private key location
private_key_location: /home/ansible/.ssh/aws/Frankfurt.pem
# AWS region
AWS_REGION: eu-central-1
# Variables used by VPC role
vpc_name: "VPC1"
vpc_cidr_block: 10.0.1.0/24
private_subnet_cidr_block: 10.0.1.0/25
public_subnet_cidr_block: 10.0.1.128/25
project_env: development
# EC2 Instance deployment
key_name: Frankfurt
instance_type: t3.micro
image_id: ami-05c26ae4789875080
