---
# Configure SSH
- name: Configure SSH
  include_role:
    name: ssh

# Configure users
- name: Configure users
  include_role:
    name: users

# - name: Install nginx packages

# - name: Install PHP packages

# - name: Configure nginx

# - name: Configure PHP