---
- name: Create webserver hosts
  include_role:
    name: provisioning
  vars:
    instance_name: "{{ item }}"
    instance_role: "webserver"
    subnet_id: "{{ private_subnet_id }}"
    security_group: "{{ webserver_sg_id }}"
  with_items:
    - "{{ webserver_host_name }}"

- name: Set webserver instance ids to a fact
  vars:
    fact_string: "{{ item }}_instance_info"
  set_fact:
    "{{ item }}_host_id": "{{ hostvars['localhost'][fact_string].instance_ids | join }}"
    "{{ item }}_host_ip": "{{ hostvars['localhost'][fact_string].instances[0].private_ip_address }}"
  with_items:
    - "{{ webserver_host_name }}"

- name: Add private ip to in-memory group
  vars:
    ip_string: "{{ item }}_host_ip"
  add_host:
    hostname: "{{ item }}"
    ansible_host: "{{ hostvars['localhost'][ip_string] }}"
    groups:
      - webserver
  with_items:
    - "{{ webserver_host_name }}"