---
# https://encoretechnologies.github.io/blog/2018/06/ansiblepatchingautomation/
- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Update packages...
  apt:
    upgrade: dist
    update_cache: yes

- name: Reboot if kernel was updated and reboot is requested by the system
  shell: 'sleep 5 && /sbin/shutdown -r now'
  args:
    removes: /var/run/reboot-required
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for system to come back from reboot...
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 180