---
- name: Wait for any possibly running unattended upgrade to finish
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Update packages...
  apt:
    upgrade: dist
    update_cache: yes

- name: Reboot
  shell: 'sleep 5 && reboot'
  async: 1
  poll: 0

- name: Waiting for system to come back from reboot...
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 180