---
- name: Create bastion host
  include_role:
    name: provisioning
  vars:
    instance_name: "{{ item }}"
    instance_role: "bastion"
    subnet_id: "{{ public_subnet_id }}"
    security_group: "{{ bastion_sg_id }}"
  with_items:
    - "{{ bastion_host_name }}"

- name: Set bastion instance id to a fact
  vars:
    fact_string: "{{ item }}_instance_info"
  set_fact:
    "{{ item }}_host_id": "{{ hostvars['localhost'][fact_string].instance_ids | join }}"
  with_items:
    - "{{ bastion_host_name }}"

- name: Assign elastic IP to bastion host
  ec2_eip:
    device_id: "{{ item }}"
    in_vpc: true
    state: present
  register: elastic_ip
  with_items:
    - "{{ bastion_host_id }}"

- name: Set bastion host IP to a variable
  set_fact:
    "{{ item }}_ip": "{{ elastic_ip.results | map(attribute='public_ip') | join }}"
  with_items:
    - "{{ bastion_host_name }}"

- name: Add public_ip to in-memory group
  vars:
    ip_string: "{{ item }}_ip"
  add_host:
    hostname: "{{ item }}"
    ansible_host: "{{ hostvars['localhost'][ip_string] }}"
    groups:
      - bastion
  with_items:
    - "{{ bastion_host_name }}"

- name: Create dynamic inventory file
  template:
    src: aws_ec2.j2
    dest: ./aws_ec2.yml
