---
- hosts: database
  become: true
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION  }}"
  vars_files:
    - keys
  tasks:
    - name: Configure backups
      include_role:
        name: duplicity
      vars:
        configure_duplicity_backups: True
