---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION  }}"
  vars_files:
    - keys
  tasks:
    - name: Get VPC information
      include_role: 
        name: vpc
      vars:
        fetch_vpc_info: True
    - name: Deploy bastion host
      include_role: 
        name: bastion
