---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION  }}"
  vars_files:
    - keys
  tasks:
    - name: Get VPC information
      include_role: 
        name: vpc
      vars:
        fetch_vpc_info: True
      when: hostvars['localhost']['create_initial_vpc'] is not defined
    - name: Create DNS entry
      include_role:
        name: route53
      vars:
        dns_name: "{{ zabbix_webui_url }}"
        dns_ip: "{% if create_initial_vpc is defined and domain_name != ''  %}{{ monitoring_host_name }}_ip{% else %}{{ hostvars['localhost']['monitoring_ip'] }}{% endif %}"

- hosts: monitoring
  become: true
  vars:
    ansible_ssh_common_args: "-o ProxyCommand='ssh -o StrictHostKeyChecking=no -i {{ private_key_location }} -W %h:%p -q ubuntu@{{ hostvars['localhost']['bastion_ip'] }}'"
  vars_files:
    - keys
  tasks:
    - name: Patch monitoring host
      include_role:
        name: patching
      when: hostvars['localhost']['create_initial_vpc'] is defined
    - name: Configure monitoring
      include_role:
        name: zabbix
      vars:
        configure_monitoring_host: True
      when: hostvars['localhost']['create_initial_vpc'] is defined

- hosts: monitoring
  become: true
  vars_files:
    - keys
  tasks:
    - name: Configure monitoring host
      include_role:
        name: zabbix
      vars:
        configure_monitoring_host: True
      when: hostvars['localhost']['create_initial_vpc'] is not defined