---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION  }}"
  vars_files:
    - keys
  tasks:
    - name: Get VPC information
      include_role: 
        name: vpc
      vars:
        fetch_vpc_info: True
      when: hostvars['localhost']['create_initial_vpc'] is not defined

- hosts: monitoring
  gather_facts: no
  become: true
  vars:
    ansible_ssh_common_args: "-o ProxyCommand='ssh -o StrictHostKeyChecking=no -i {{ private_key_location }} -W %h:%p -q ubuntu@{{ hostvars['localhost']['bastion_ip'] }}'"
  tasks:
    - name: Patch bastion host
      include_role:
        name: patching
      when: hostvars['localhost']['create_initial_vpc'] is defined
    - name: Configure monitoring
      include_role:
        name: zabbix
      vars:
        configure_monitoring_host: True
      when: hostvars['localhost']['create_initial_vpc'] is defined

- hosts: monitoring
  gather_facts: no
  become: true
  tasks:
    - name: Configure monitoring host
      include_role:
        name: zabbix
      vars:
        configure_monitoring_host: True
      when: hostvars['localhost']['create_initial_vpc'] is not defined