---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
    AWS_REGION: "{{ AWS_REGION  }}"
  vars_files:
    - keys.yml
  tasks:
    - name: Include VPC role
      include_role: 
        name: "{{ role_name }}"
      vars:
        create_initial_vpc: True
      loop:
        - vpc
        - bastion
        - mysql
        - nginx
        - zabbix
      loop_control:
        loop_var: role_name