---
- name: Create webserver hosts
  include_role:
    name: provisioning
  vars:
    service_name: "nginx"
    service_role: "webserver"
    subnet_id: "{{ private_subnet_id }}"
    security_group: "{{ webserver_sg_id }}"
    count: "2"

- name: Set webserver instance ids to a fact
  set_fact:
    webserver_host_id: "{{ webserver_instance_info.instances | map(attribute='instance_id') | join }}"
