---
- name: Create {{ instance_name }} instance
  ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ subnet_id }}"
    security_group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    state: running
    wait: yes
    wait_timeout: 60
    tags:
      Role: "{{ instance_role }}"
      Environment: "{{ project_env }}"
  register: instance_info

- name: Set instance information to a fact
  set_fact:
    "{{ instance_name }}_instance_info": "{{ instance_info }}"
