---
- name: Create {{ service_name }} instance
  ec2_instance:
    name: "{{ service_name }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ subnet_id }}"
    security_group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    wait: yes
    tags:
      Role: "{{ service_role }}"
      Environment: "{{ project_env }}"


