---
- name: Create route table for private subnet
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    subnets: "{{ private_subnet_id }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ nat_gateway_id }}"
    tags:
      Name: "{{ vpc_id }}_private_rt"