- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ AWS_REGION }}"
    state: present
    tags:
      Name: "{{ vpc_name }}"
      Environment: "{{ project_env }}"
  register: deployed_vpc

- name: Assign VPC ID to a variable
  set_fact:
    vpc_id: "{{ deployed_vpc.vpc.id }}"