---
- name: Create security group for db servers
  ec2_group:
    name: "{{ vpc_name }}_database_sg"
    description: "SG for db servers"
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: "{{ vpc_name }}_database_sg"
      Environment: "{{ project_env }}"
  register: database_sg

- name: Assign db servers security group ID to a variable
  set_fact:
    database_sg_id: "{{ database_sg.group_id }}"
    database_sg_owner: "{{ database_sg.owner_id }}"
    database_sg_name: "{{ database_sg.group_name }}"