---
- name: Create security group for db servers
  ec2_group:
    name: "{{ vpc_name }}_db_sg"
    description: "SG for db servers"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        group_id: "{{ webserver_sg_owner }}/{{ webserver_sg_id }}/{{ webserver_sg_name }}"
      - proto: tcp
        from_port: 10050
        to_port: 10050
        group_id: "{{ monitoring_sg_owner }}/{{ monitoring_sg_id }}/{{ monitoring_sg_name }}"

    tags:
      environment: "{{ project_env }}"
  register: db_sg

- name: Assign db servers security group ID to a variable
  set_fact:
    db_sg_id: "{{ db_sg.group_id }}"