---
- name: Create security group for db servers
  ec2_group:
    name: "{{ vpc_name }}_database_sg"
    description: "SG for db servers"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        group_id: "{{ webserver_sg_owner }}/{{ webserver_sg_id }}/{{ webserver_sg_name }}"
      - proto: tcp
        from_port: 10050
        to_port: 10050
        group_id: "{{ monitoring_sg_owner }}/{{ monitoring_sg_id }}/{{ monitoring_sg_name }}"
      - proto: tcp
        from_port: 22
        to_port: 22
        group_id: "{{ bastion_sg_owner }}/{{ bastion_sg_id }}/{{ bastion_sg_name }}"
    tags:
      Name: "{{ vpc_name }}_database_sg"
      Environment: "{{ project_env }}"
  register: database_sg

- name: Assign db servers security group ID to a variable
  set_fact:
    database_sg_id: "{{ database_sg.group_id }}"