---
- name: Create internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    state: present
    tags:
      VPC: "{{ vpc_name }}"
  register: igw

- name: Set internet gateway ID to a variable
  set_fact:
    igw_id: "{{ igw.gateway_id }}"