---
- name: Deploy initial VPC
  include_tasks: deploy_vpc.yml
  when: create_initial_vpc is defined and create_initial_vpc == True

- name: Gather VPC information
  include_tasks: get_vpc_information.yml
  when: fetch_vpc_info is defined and fetch_vpc_info == True
