---
# Configure SSH options
- name: Configure SSH
  include_role:
    name: ssh

# Configure users
- name: Configure users
  include_role:
    name: users

# Configure autopatching
# - name: Configure autopatching
#   include_role:
#     name: patching