---
# Configure SSH options
- name: Configure SSH
  include_role:
    name: ssh

# Configure users
- name: Configure users
  include_role:
    name: users

- name: Install and configure Zabbix
  include_tasks: configure_zabbix.yml