---
- name: Create monitoring host
  include_role:
    name: provisioning
  vars:
    service_name: "zabbix"
    service_role: "monitoring"
    subnet_id: "{{ public_subnet_id }}"
    security_group: "{{ monitoring_sg_id }}"
    count: "1"

- name: Set zabbix instance id to a fact
  set_fact:
    monitoring_host_id: "{{ monitoring_instance_info.instances | map(attribute='instance_id') | join }}"

- name: Assign elastic IP to monitoring host
  ec2_eip:
    device_id: "{{ monitoring_host_id }}"
    in_vpc: true
    state: present
  register: elastic_ip

- name: Set monitoring host IP to a variable
  set_fact:
    monitoring_ip: "{{ elastic_ip.public_ip }}"